travis:
  secure:
    BINSTAR_TOKEN: E16qpbWc9PyOvt48c21DhRf2a39ZqESc1UgzdJLVXdRqocsRqYRTBIH0M7dqsyJzam2ljA5PVcCDRS2GynJEoRGvYnuuae7X5icyKkgSs+2Mv+6L8cd+g4G/2nH4qvO6ZmLcElW5V1Xq5W0x+hcjAEF/iiIPBGpFGXK0lmB/zp6emH9VBanysFzk7iGVTygUPnuKZUPFQkdLv3v9xeudVwLbeudNAlkUjjeQZhtuwUcyefW407umnmTErmMOpmaURjkNmtI1zQEuNClc35kywZNzebeONLNeQh73dupKiC3k2XnL5NFA20XlYigtIivvQhwl3qH49IVWIgRsG8JvBYHY7By9FwPQ14mDz2HRkl6xDGXOhftLRjWpq0En7NLOUaZJV/5PgoWYhYI6porEMwz1Mv8wTgKbVV4Fo8PGnMknSzvez8IZ1ZoD7aKvLfEkjtyqdjqLFUw0P5ZEOATzm2Lk4ni3U9THSdNRNjKmvAoUuwsf/B++GFTqA/uCuKF2UKvEknVjQRCQbGMEc5tUjOMsefbG2KAw98+sl5qjk3+yxtbXrWj5Hn3NmqdGImVhhcV4lcM53jUJdbCb2WJJ7kkGiv+aLA811W5i4ZqxBscCjSyjg+6GWu+cvqGNvEGsn6anWNq57aPEDtexlUpxtEIVLFgh8KcEII5lqyba7co=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
