travis:
  secure:
    BINSTAR_TOKEN: ZJ0zSsvFrwZ1MlPa0otJS7fwgTiuSeWC5/yI9zogQ/lm0VsIftVKEHd7dzt4OqTCyBzp0edwwz9zEbB7xwpkJrqZrLDWSljWQKFqTBlnFjH565xKQkE3/eU7eUFt2ObekcMN/j5di0R1wp010tNky6J+BgLndvq/ArQDWWMWOtebYjWxHRe0jTody+0s/dKb/6EdXNlBDuN6S9EeGwHDy8TGj0qgJ7Z00LutZKGy5ya1GnonuzVl0NjK/nF3ewuagErRPTz86HqHtkn0ycOnVRnugqRBexbm7KPFBvGbDZdnVtbf8JjJsgWCRrOR88JUj+JozdjL3UlkDJiOu7Qertq37NO/IH3vOsU30KnBNu8Gh42IcJxQrQVbTzl4P0JqeTioR25o7kOwzhjojDeHMdX6skZ7ifq3oiNhsEuNwjy7AdfXcsXgRLP5Iu2DQjzCmKfmj0w6X9PgqYj6sFVhB9xrGDhM1xBF6UIwFDb8kg4lQ1nU9mhfGot3pscszNih0MqjRraa4KF3S3Svbm1O5whHSkp883C5gIMoPRZMR7KrdvXrin88H9JqlhIxGsTbaM4eqrQlPFCSyCSnKdZwwjZFHsR61jXLlL+b89IHLf6nG6Es+cOU4OEph2TLmM9Ukx/V5FYWM3AhcNHwCDcvoNMnnEW6DvxHV9ch/Dksw64=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
